# .readthedocs.yml
version: 2
build:
  image: "ubuntu-20.04"  # 用于构建网站的镜像
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
    conda: "latest"
    sphinx: "latest"
  conda:
    environment_file: environment.yml  # 指定你的 environment.yml 文件路径
  commands:
    - pip install -r requirements.txt  # 如果你有其他依赖，可以在此安装

python:
  install:
    - method: pip
      path: .  # 从当前目录安装
  version: "3.8"  # 如果需要指定 Python 版本，可以在此修改